export const USERS_DUMMY = [
  // KLAPANUNGGAL
  {
    name: "Siti",
    email: "siti@agrobot.co.id",
    phone: "081234567801",
    password: "siti123",
    locationId: "klapanunggal",
    role: "field_assistant",
    roleSub: "FA-01",
    status: "Aktif",
  },
  {
    name: "Agus",
    email: "agus@agrobot.co.id",
    phone: "081234567802",
    password: "agus123",
    locationId: "klapanunggal",
    role: "water_expert",
    roleSub: "WE-01",
    status: "Aktif",
  },
  {
    name: "Budi",
    email: "budi@agrobot.co.id",
    phone: "081234567803",
    password: "budi123",
    locationId: "klapanunggal",
    role: "grower",
    roleSub: "GH-01",
    status: "Aktif",
  },
  {
    name: "Rudi",
    email: "rudi@agrobot.co.id",
    phone: "081234567804",
    password: "rudi123",
    locationId: "klapanunggal",
    role: "grower",
    roleSub: "GH-02",
    status: "Aktif",
  },
  {
    name: "Tono",
    email: "tono@agrobot.co.id",
    phone: "081234567805",
    password: "tono123",
    locationId: "klapanunggal",
    role: "grower",
    roleSub: "GH-03",
    status: "Aktif",
  },

  // LIDO
  {
    name: "Dedi",
    email: "dedi@agrobot.co.id",
    phone: "081234567806",
    password: "dedi123",
    locationId: "lido",
    role: "field_assistant",
    roleSub: "FA-01",
    status: "Aktif",
  },
  {
    name: "Yusuf",
    email: "yusuf@agrobot.co.id",
    phone: "081234567807",
    password: "yusuf123",
    locationId: "lido",
    role: "water_expert",
    roleSub: "WE-01",
    status: "Aktif",
  },
  {
    name: "Asep",
    email: "asep@agrobot.co.id",
    phone: "081234567808",
    password: "asep123",
    locationId: "lido",
    role: "grower",
    roleSub: "GH-01",
    status: "Aktif",
  },
  {
    name: "Wawan",
    email: "wawan@agrobot.co.id",
    phone: "081234567809",
    password: "wawan123",
    locationId: "lido",
    role: "grower",
    roleSub: "GH-02",
    status: "Aktif",
  },
  {
    name: "Rizal",
    email: "rizal@agrobot.co.id",
    phone: "081234567810",
    password: "rizal123",
    locationId: "lido",
    role: "grower",
    roleSub: "GH-03",
    status: "Aktif",
  },

  // PADALARANG
  {
    name: "Mang Ujang",
    email: "ujang@agrobot.co.id",
    phone: "081234567811",
    password: "ujang123",
    locationId: "padalarang",
    role: "field_assistant",
    roleSub: "FA-01",
    status: "Aktif",
  },
  {
    name: "Herman",
    email: "herman@agrobot.co.id",
    phone: "081234567812",
    password: "herman123",
    locationId: "padalarang",
    role: "water_expert",
    roleSub: "WE-01",
    status: "Aktif",
  },
  {
    name: "Doni",
    email: "doni@agrobot.co.id",
    phone: "081234567813",
    password: "doni123",
    locationId: "padalarang",
    role: "grower",
    roleSub: "GH-01",
    status: "Aktif",
  },
  {
    name: "Jaka",
    email: "jaka@agrobot.co.id",
    phone: "081234567814",
    password: "jaka123",
    locationId: "padalarang",
    role: "grower",
    roleSub: "GH-02",
    status: "Aktif",
  },
  {
    name: "Fajar",
    email: "fajar@agrobot.co.id",
    phone: "081234567815",
    password: "fajar123",
    locationId: "padalarang",
    role: "grower",
    roleSub: "GH-03",
    status: "Aktif",
  },

  // INDRAMAYU
  {
    name: "Rahmat",
    email: "rahmat@agrobot.co.id",
    phone: "081234567816",
    password: "rahmat123",
    locationId: "indramayu",
    role: "field_assistant",
    roleSub: "FA-01",
    status: "Aktif",
  },
  {
    name: "Bagus",
    email: "bagus@agrobot.co.id",
    phone: "081234567817",
    password: "bagus123",
    locationId: "indramayu",
    role: "water_expert",
    roleSub: "WE-01",
    status: "Aktif",
  },
  {
    name: "Slamet",
    email: "slamet@agrobot.co.id",
    phone: "081234567818",
    password: "slamet123",
    locationId: "indramayu",
    role: "grower",
    roleSub: "GH-01",
    status: "Aktif",
  },
  {
    name: "Yanto",
    email: "yanto@agrobot.co.id",
    phone: "081234567819",
    password: "yanto123",
    locationId: "indramayu",
    role: "grower",
    roleSub: "GH-02",
    status: "Aktif",
  },
  {
    name: "Udin",
    email: "udin@agrobot.co.id",
    phone: "081234567820",
    password: "udin123",
    locationId: "indramayu",
    role: "grower",
    roleSub: "GH-03",
    status: "Aktif",
  },
];
